-- Seed the canonical biomarker dictionary (~58 analytes) + lab-name aliases.
-- Seeded via MIGRATION (not seed.sql) so `supabase db push` applies it to the
-- hosted project too. Idempotent: safe to re-run.
--
-- Aliases are the moat — grow this table with every new lab PDF. All aliases
-- are lowercase (enforced by check + unique-on-lower index).

insert into public.biomarkers (code, display_name, category, canonical_unit) values
  -- CBC
  ('hemoglobin',        'Hemoglobin',                     'CBC',          'g/dL'),
  ('rbc',               'RBC Count',                      'CBC',          'million/µL'),
  ('wbc',               'WBC / Total Leukocyte Count',    'CBC',          'thousand/µL'),
  ('platelets',         'Platelet Count',                 'CBC',          'thousand/µL'),
  ('hematocrit',        'Hematocrit (PCV)',               'CBC',          '%'),
  ('mcv',               'MCV',                            'CBC',          'fL'),
  ('mch',               'MCH',                            'CBC',          'pg'),
  ('mchc',              'MCHC',                           'CBC',          'g/dL'),
  ('rdw',               'RDW',                            'CBC',          '%'),
  ('neutrophils',       'Neutrophils',                    'CBC',          '%'),
  ('lymphocytes',       'Lymphocytes',                    'CBC',          '%'),
  ('monocytes',         'Monocytes',                      'CBC',          '%'),
  ('eosinophils',       'Eosinophils',                    'CBC',          '%'),
  ('basophils',         'Basophils',                      'CBC',          '%'),
  ('esr',               'ESR',                            'Inflammation', 'mm/hr'),
  -- Lipid
  ('total_cholesterol', 'Total Cholesterol',              'Lipid',        'mg/dL'),
  ('hdl',               'HDL Cholesterol',                'Lipid',        'mg/dL'),
  ('ldl',               'LDL Cholesterol',                'Lipid',        'mg/dL'),
  ('vldl',              'VLDL Cholesterol',               'Lipid',        'mg/dL'),
  ('triglycerides',     'Triglycerides',                  'Lipid',        'mg/dL'),
  ('non_hdl',           'Non-HDL Cholesterol',            'Lipid',        'mg/dL'),
  -- Liver (LFT)
  ('alt',               'ALT (SGPT)',                     'LFT',          'U/L'),
  ('ast',               'AST (SGOT)',                     'LFT',          'U/L'),
  ('alp',               'Alkaline Phosphatase',           'LFT',          'U/L'),
  ('ggt',               'GGT',                            'LFT',          'U/L'),
  ('bilirubin_total',   'Bilirubin, Total',               'LFT',          'mg/dL'),
  ('bilirubin_direct',  'Bilirubin, Direct',              'LFT',          'mg/dL'),
  ('bilirubin_indirect','Bilirubin, Indirect',            'LFT',          'mg/dL'),
  ('total_protein',     'Total Protein',                  'LFT',          'g/dL'),
  ('albumin',           'Albumin',                        'LFT',          'g/dL'),
  ('globulin',          'Globulin',                       'LFT',          'g/dL'),
  ('ag_ratio',          'A/G Ratio',                      'LFT',          'ratio'),
  -- Kidney (KFT)
  ('urea',              'Blood Urea',                     'KFT',          'mg/dL'),
  ('bun',               'Blood Urea Nitrogen (BUN)',      'KFT',          'mg/dL'),
  ('creatinine',        'Creatinine',                     'KFT',          'mg/dL'),
  ('uric_acid',         'Uric Acid',                      'KFT',          'mg/dL'),
  ('egfr',              'eGFR',                            'KFT',          'mL/min/1.73m²'),
  ('sodium',            'Sodium',                         'KFT',          'mmol/L'),
  ('potassium',         'Potassium',                      'KFT',          'mmol/L'),
  ('chloride',          'Chloride',                       'KFT',          'mmol/L'),
  ('calcium',           'Calcium',                        'KFT',          'mg/dL'),
  ('phosphorus',        'Phosphorus',                     'KFT',          'mg/dL'),
  -- Thyroid
  ('tsh',               'TSH',                            'Thyroid',      'µIU/mL'),
  ('t3',                'T3 (Total)',                     'Thyroid',      'ng/dL'),
  ('t4',                'T4 (Total)',                     'Thyroid',      'µg/dL'),
  ('ft3',               'Free T3',                        'Thyroid',      'pg/mL'),
  ('ft4',               'Free T4',                        'Thyroid',      'ng/dL'),
  -- Glucose
  ('glucose_fasting',   'Fasting Blood Glucose',          'Glucose',      'mg/dL'),
  ('glucose_pp',        'Post-Prandial Blood Glucose',    'Glucose',      'mg/dL'),
  ('glucose_random',    'Random Blood Glucose',           'Glucose',      'mg/dL'),
  ('hba1c',             'HbA1c',                          'Glucose',      '%'),
  ('insulin_fasting',   'Fasting Insulin',                'Glucose',      'µIU/mL'),
  -- Vitamins
  ('vitamin_d',         'Vitamin D (25-OH)',              'Vitamins',     'ng/mL'),
  ('vitamin_b12',       'Vitamin B12',                    'Vitamins',     'pg/mL'),
  ('folate',            'Folate',                         'Vitamins',     'ng/mL'),
  -- Iron studies
  ('iron',              'Serum Iron',                     'Iron',         'µg/dL'),
  ('ferritin',          'Ferritin',                       'Iron',         'ng/mL'),
  ('tibc',              'TIBC',                            'Iron',         'µg/dL'),
  ('transferrin_sat',   'Transferrin Saturation',         'Iron',         '%'),
  -- Inflammation
  ('crp',               'C-Reactive Protein (CRP)',       'Inflammation', 'mg/L')
on conflict (code) do update
  set display_name   = excluded.display_name,
      category       = excluded.category,
      canonical_unit = excluded.canonical_unit;

-- Aliases: lab-specific names → canonical code. Lowercase only.
insert into public.biomarker_aliases (biomarker_id, alias)
select b.id, a.alias
from (values
  ('hemoglobin',        'hemoglobin'),
  ('hemoglobin',        'haemoglobin'),
  ('hemoglobin',        'hb'),
  ('hemoglobin',        'hgb'),
  ('rbc',               'rbc count'),
  ('rbc',               'total rbc count'),
  ('rbc',               'red blood cell count'),
  ('rbc',               'erythrocyte count'),
  ('wbc',               'wbc count'),
  ('wbc',               'total wbc count'),
  ('wbc',               'total leukocyte count'),
  ('wbc',               'tlc'),
  ('wbc',               'white blood cell count'),
  ('platelets',         'platelet count'),
  ('platelets',         'platelets'),
  ('platelets',         'plt'),
  ('hematocrit',        'hematocrit'),
  ('hematocrit',        'haematocrit'),
  ('hematocrit',        'pcv'),
  ('hematocrit',        'packed cell volume'),
  ('mcv',               'mcv'),
  ('mcv',               'mean corpuscular volume'),
  ('mch',               'mch'),
  ('mch',               'mean corpuscular hemoglobin'),
  ('mchc',              'mchc'),
  ('rdw',               'rdw'),
  ('rdw',               'rdw-cv'),
  ('rdw',               'red cell distribution width'),
  ('neutrophils',       'neutrophils'),
  ('neutrophils',       'neutrophil'),
  ('neutrophils',       'polymorphs'),
  ('lymphocytes',       'lymphocytes'),
  ('lymphocytes',       'lymphocyte'),
  ('monocytes',         'monocytes'),
  ('eosinophils',       'eosinophils'),
  ('basophils',         'basophils'),
  ('esr',               'esr'),
  ('esr',               'erythrocyte sedimentation rate'),
  ('total_cholesterol', 'total cholesterol'),
  ('total_cholesterol', 'cholesterol total'),
  ('total_cholesterol', 'cholesterol'),
  ('total_cholesterol', 'serum cholesterol'),
  ('hdl',               'hdl'),
  ('hdl',               'hdl cholesterol'),
  ('hdl',               'hdl - cholesterol'),
  ('hdl',               'high density lipoprotein'),
  ('ldl',               'ldl'),
  ('ldl',               'ldl cholesterol'),
  ('ldl',               'ldl - cholesterol'),
  ('ldl',               'low density lipoprotein'),
  ('vldl',              'vldl'),
  ('vldl',              'vldl cholesterol'),
  ('triglycerides',     'triglycerides'),
  ('triglycerides',     'triglyceride'),
  ('triglycerides',     'tg'),
  ('non_hdl',           'non-hdl cholesterol'),
  ('non_hdl',           'non hdl cholesterol'),
  ('alt',               'alt'),
  ('alt',               'sgpt'),
  ('alt',               'alt (sgpt)'),
  ('alt',               'sgpt (alt)'),
  ('alt',               'alanine aminotransferase'),
  ('alt',               'alanine transaminase'),
  ('ast',               'ast'),
  ('ast',               'sgot'),
  ('ast',               'ast (sgot)'),
  ('ast',               'sgot (ast)'),
  ('ast',               'aspartate aminotransferase'),
  ('ast',               'aspartate transaminase'),
  ('alp',               'alp'),
  ('alp',               'alkaline phosphatase'),
  ('alp',               'serum alkaline phosphatase'),
  ('ggt',               'ggt'),
  ('ggt',               'gamma gt'),
  ('ggt',               'gamma glutamyl transferase'),
  ('bilirubin_total',   'bilirubin total'),
  ('bilirubin_total',   'total bilirubin'),
  ('bilirubin_total',   'bilirubin (total)'),
  ('bilirubin_total',   'serum bilirubin total'),
  ('bilirubin_direct',  'bilirubin direct'),
  ('bilirubin_direct',  'direct bilirubin'),
  ('bilirubin_direct',  'bilirubin (direct)'),
  ('bilirubin_direct',  'conjugated bilirubin'),
  ('bilirubin_indirect','bilirubin indirect'),
  ('bilirubin_indirect','indirect bilirubin'),
  ('bilirubin_indirect','unconjugated bilirubin'),
  ('total_protein',     'total protein'),
  ('total_protein',     'total proteins'),
  ('total_protein',     'serum total protein'),
  ('albumin',           'albumin'),
  ('albumin',           'serum albumin'),
  ('globulin',          'globulin'),
  ('ag_ratio',          'a/g ratio'),
  ('ag_ratio',          'a:g ratio'),
  ('ag_ratio',          'albumin/globulin ratio'),
  ('urea',              'urea'),
  ('urea',              'blood urea'),
  ('urea',              'serum urea'),
  ('bun',               'bun'),
  ('bun',               'blood urea nitrogen'),
  ('creatinine',        'creatinine'),
  ('creatinine',        'serum creatinine'),
  ('uric_acid',         'uric acid'),
  ('uric_acid',         'serum uric acid'),
  ('egfr',              'egfr'),
  ('egfr',              'estimated gfr'),
  ('egfr',              'gfr'),
  ('sodium',            'sodium'),
  ('sodium',            'na'),
  ('sodium',            'na+'),
  ('potassium',         'potassium'),
  ('potassium',         'k'),
  ('potassium',         'k+'),
  ('chloride',          'chloride'),
  ('chloride',          'cl'),
  ('chloride',          'cl-'),
  ('calcium',           'calcium'),
  ('calcium',           'serum calcium'),
  ('calcium',           'total calcium'),
  ('phosphorus',        'phosphorus'),
  ('phosphorus',        'phosphorous'),
  ('phosphorus',        'inorganic phosphorus'),
  ('tsh',               'tsh'),
  ('tsh',               'thyroid stimulating hormone'),
  ('tsh',               'tsh - ultrasensitive'),
  ('t3',                't3'),
  ('t3',                'total t3'),
  ('t3',                'triiodothyronine'),
  ('t4',                't4'),
  ('t4',                'total t4'),
  ('t4',                'thyroxine'),
  ('ft3',               'ft3'),
  ('ft3',               'free t3'),
  ('ft3',               'free triiodothyronine'),
  ('ft4',               'ft4'),
  ('ft4',               'free t4'),
  ('ft4',               'free thyroxine'),
  ('glucose_fasting',   'fasting blood sugar'),
  ('glucose_fasting',   'fasting blood glucose'),
  ('glucose_fasting',   'fbs'),
  ('glucose_fasting',   'glucose fasting'),
  ('glucose_fasting',   'blood sugar fasting'),
  ('glucose_pp',        'post prandial blood sugar'),
  ('glucose_pp',        'postprandial blood glucose'),
  ('glucose_pp',        'ppbs'),
  ('glucose_pp',        'pp blood sugar'),
  ('glucose_pp',        'blood sugar pp'),
  ('glucose_random',    'random blood sugar'),
  ('glucose_random',    'rbs'),
  ('glucose_random',    'random blood glucose'),
  ('hba1c',             'hba1c'),
  ('hba1c',             'hba1c (glycated hemoglobin)'),
  ('hba1c',             'glycated hemoglobin'),
  ('hba1c',             'glycosylated hemoglobin'),
  ('hba1c',             'hemoglobin a1c'),
  ('insulin_fasting',   'fasting insulin'),
  ('insulin_fasting',   'insulin fasting'),
  ('vitamin_d',         'vitamin d'),
  ('vitamin_d',         'vitamin d (25-oh)'),
  ('vitamin_d',         '25-oh vitamin d'),
  ('vitamin_d',         '25 hydroxy vitamin d'),
  ('vitamin_d',         'vitamin d total'),
  ('vitamin_b12',       'vitamin b12'),
  ('vitamin_b12',       'vitamin b-12'),
  ('vitamin_b12',       'b12'),
  ('vitamin_b12',       'cyanocobalamin'),
  ('folate',            'folate'),
  ('folate',            'folic acid'),
  ('folate',            'serum folate'),
  ('iron',              'iron'),
  ('iron',              'serum iron'),
  ('ferritin',          'ferritin'),
  ('ferritin',          'serum ferritin'),
  ('tibc',              'tibc'),
  ('tibc',              'total iron binding capacity'),
  ('transferrin_sat',   'transferrin saturation'),
  ('transferrin_sat',   'transferrin saturation (%)'),
  ('transferrin_sat',   'tsat'),
  ('crp',               'crp'),
  ('crp',               'c-reactive protein'),
  ('crp',               'c reactive protein'),
  ('crp',               'crp quantitative')
) as a(code, alias)
join public.biomarkers b on b.code = a.code
on conflict (lower(alias)) do nothing;
